#cloud-config
# vim: syntax=yaml

user: cloud
ssh_pwauth: True
chpasswd:
    list: |
        root:contrail123
        cloud:contrail123
    expire: False

package_update: true
package_upgrade: true
package_reboot_if_required: false

packages:
  - git
  - subversion
  - mc
  - vim
  - traceroute
  - htop
  - mosh
  - tmux
  - screen
  - jq
  - libpq-dev  # rally

output: {all: '| tee -a /var/log/cloud-init-output.log'}

runcmd:
  - [ sh, -xc, "su cloud -c 'cd && git clone https://github.com/nojhan/liquidprompt.git'" ]
  - [ sh, -xc, "su cloud -c 'echo source ~/liquidprompt/liquidprompt >> /home/cloud/.bashrc'" ]
  - [ sh, -xc, "su cloud -c 'git config --global http.sslVerify false'"]
  - [ sh, -xc, "su cloud -c 'bash /opt/build.sh'" ]

write_files:
-   content: |
        #!/usr/bin/env bash
        tmux new-session -s opencontrail -n shell -d
        tmux new-window -t opencontrail:1 -n stack
        tmux send-keys -t opencontrail:1 'cd ~/ && git clone https://github.com/openstack-dev/devstack.git && cd devstack && git checkout stable/mitaka && cp /opt/local.conf . && ./stack.sh' C-m
    path: /opt/build.sh
    permissions: 0775
-   content: |
        [[local|localrc]]
        SERVICE_TOKEN=azertytoken
        ADMIN_PASSWORD=contrail123
        MYSQL_PASSWORD=stackdb
        RABBIT_PASSWORD=stackqueue
        SERVICE_PASSWORD=$ADMIN_PASSWORD
        LOGFILE=$DEST/logs/stack.sh.log
        LOGDAYS=2
        SWIFT_HASH=66a3d6b56c1f479c8b4e70ab5c2000f5
        SWIFT_REPLICAS=1
        SWIFT_DATA_DIR=$DEST/data
        disable_service n-net
        enable_service q-svc
        enable_service q-agt
        enable_service q-dhcp
        enable_service q-l3
        enable_service q-meta
        enable_service tempest

        ## Neutron options
        Q_USE_SECGROUP=True
        FLOATING_RANGE="172.18.161.0/24"
        FIXED_RANGE="10.0.0.0/24"
        Q_FLOATING_ALLOCATION_POOL=start=172.18.161.2,end=172.18.161.254
        PUBLIC_NETWORK_GATEWAY="172.18.161.1"
        PUBLIC_INTERFACE=eth0

        # Open vSwitch provider networking configuration
        Q_USE_PROVIDERNET_FOR_PUBLIC=True
        OVS_PHYSICAL_BRIDGE=br-ex
        PUBLIC_BRIDGE=br-ex
        OVS_BRIDGE_MAPPINGS=public:br-ex

    path: /opt/local.conf
    permissions: 0664
