#cloud-config
# vim: syntax=yaml

user: cloud
ssh_pwauth: True
chpasswd:
    list: |
        root:contrail123
        cloud:contrail123
    expire: False

package_update: true
package_upgrade: true
package_reboot_if_required: false

packages:
  - git
  - subversion
  - mc
  - vim
  - traceroute
  - htop
  - mosh
  - tmux
  - screen
  - jq
  - libpq-dev  # rally
  - liberasurecode-dev # PyECLib

apt_sources:
  - source: deb http://archive.ubuntu.com/ubuntu trusty-backports universe

final_message: "!!! Starting building OpenContrail !!! (cloudinit runs in $UPTIME seconds)"

output: {all: '| tee -a /var/log/cloud-init-output.log'}

runcmd:
  - [ sh, -xc, "su cloud -c 'cd && git clone https://github.com/nojhan/liquidprompt.git'" ]
  - [ sh, -xc, "su cloud -c 'echo source ~/liquidprompt/liquidprompt >> /home/cloud/.bashrc'" ]
  - [ sh, -xc, "su cloud -c 'git config --global http.sslVerify false'"]
  - [ sh, -xc, "su cloud -c 'bash /opt/build.sh'" ]

write_files:
-   content: |
        #!/usr/bin/env bash
        tmux new-session -s opencontrail -n shell -d
        tmux new-window -t opencontrail:1 -n stack
        tmux send-keys -t opencontrail:1 'cd ~/ && git clone https://github.com/openstack-dev/devstack.git && cd devstack && git checkout mitaka-eol && cp /opt/local.conf . && (./stack.sh || ./stack.sh)' C-m
    path: /opt/build.sh
    permissions: 0775
-   content: |
        [[local|localrc]]
        SERVICE_TOKEN=azertytoken
        ADMIN_PASSWORD=contrail123
        MYSQL_PASSWORD=stackdb
        RABBIT_PASSWORD=stackqueue
        SERVICE_PASSWORD=$ADMIN_PASSWORD
        LOGFILE=$DEST/logs/stack.sh.log
        LOGDAYS=2
        SWIFT_HASH=66a3d6b56c1f479c8b4e70ab5c2000f5
        SWIFT_REPLICAS=1
        SWIFT_DATA_DIR=$DEST/data
        HOST_IP=127.0.0.1

        enable_plugin contrail https://github.com/zioc/contrail-devstack-plugin.git
        enable_plugin rally https://github.com/openstack/rally master
        enable_plugin skydive https://github.com/skydive-project/skydive.git
        enable_plugin contrail-ci https://github.com/eonpatapon/contrail-ci.git
        enable_plugin neutron-lbaas https://github.com/openstack/neutron-lbaas.git mitaka-eol

        REQUIREMENTS_REPO="https://github.com/rasta-rocket/requirements.git"
        REQUIREMENTS_BRANCH="cloudwatt-stable/mitaka"

        CINDER_BRANCH=${CINDER_BRANCH:-mitaka-eol}
        GLANCE_BRANCH=${GLANCE_BRANCH:-mitaka-eol}
        HEAT_BRANCH=${HEAT_BRANCH:-mitaka-eol}
        HORIZON_BRANCH=${HORIZON_BRANCH:-mitaka-eol}
        KEYSTONE_BRANCH=${KEYSTONE_BRANCH:-mitaka-eol}
        NEUTRON_BRANCH=${NEUTRON_BRANCH:-mitaka-eol}
        NEUTRON_FWAAS_BRANCH=${NEUTRON_FWAAS_BRANCH:-mitaka-eol}
        NEUTRON_LBAAS_BRANCH=${NEUTRON_LBAAS_BRANCH:-mitaka-eol}
        NOVA_BRANCH=${NOVA_BRANCH:-mitaka-eol}
        SWIFT_BRANCH=${SWIFT_BRANCH:-mitaka-eol}

        CONTRAIL_REPO=https://github.com/eonpatapon/contrail-vnc.git
        CONTRAIL_BRANCH=devstack
        SCONS_JOBS=$(lscpu -p | grep -cve '^#')
        VHOST_INTERFACE_NAME=eth0
        Q_L3_ENABLED=True
        VGW_MASQUERADE=True

        PUBLIC_INTERFACE=$VHOST_INTERFACE_NAME

        SKYDIVE_ANALYZER_LISTEN=0.0.0.0:8282
        SKYDIVE_ANALYZERS=${HOST_IP}:8282
        SKYDIVE_AGENT_LISTEN=${HOST_IP}:8281
        SKYDIVE_AGENT_ETCD=${HOST_IP}:2379
        SKYDIVE_AGENT_PROBES="netns netlink opencontrail neutron"
        SKYDIVE_FLOWS_STORAGE="none"
        SKYDIVE_GRAPH_STORAGE="memory"
        SKYDIVE_KEYSTONE_API_VERSION="v2.0"

        # base
        ENABLED_SERVICES=rabbit,mysql,key
        # nova
        ENABLED_SERVICES+=,n-api,n-crt,n-obj,n-cpu,n-cond,n-sch
        # neutron
        ENABLED_SERVICES+=,q-svc,q-agt,q-meta,neutron
        # glance
        ENABLED_SERVICES+=,g-api,g-reg
        # contrail
        ENABLED_SERVICES+=,vrouter,api-srv,disco,svc-mon,schema,control,collector,analytic-api,query-engine
        # skydive
        ENABLED_SERVICES+=,skydive-agent,skydive-analyzer
        # lbaas
        ENABLED_SERVICES+=,q-lbaasv1

        [[post-config|$NEUTRON_CONF]]
        [DEFAULT]
        api_extensions_path = extensions:/opt/stack/contrail/openstack/neutron_plugin/neutron_plugin_contrail/extensions:/opt/stack/neutron-lbaas/neutron_lbaas/extensions
        service_plugins = neutron_plugin_contrail.plugins.opencontrail.loadbalancer.plugin.LoadBalancerPlugin
        [service_providers]
        service_provider = LOADBALANCER:opencontrail:neutron_plugin_contrail.plugins.opencontrail.loadbalancer.driver.OpencontrailLoadbalancerDriver:default
        [quotas]
        quota_driver = neutron_plugin_contrail.plugins.opencontrail.quota.driver.QuotaDriver

    path: /opt/local.conf
    permissions: 0664
